version: '2'
services:

  react-app:
    image: basim95/react-app
    stdin_open: true
   
    
  mongo:
    image: mongo
    restart: always
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root    
      MONGO_INITDB_ROOT_PASSWORD: example   

  api-server:
    image: basim95/api-server
    ports:
      - "5000:5000"  
    depends_on:
      - mongo
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react-app  
      - api-server
